# Generated by Django 2.1.5 on 2022-08-23 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=100, verbose_name='系统名称')),
                ('level', models.CharField(choices=[('1', 'S2A2G2'), ('2', 'S2A1G2'), ('3', 'S1A2G2'), ('4', 'S3A3G3'), ('5', 'S3A2G3'), ('6', 'S2A3G3')], max_length=30, verbose_name='系统级别')),
                ('completion_time', models.DateField(blank=True, null=True, verbose_name='项目完成时间')),
            ],
            options={
                'verbose_name_plural': '奖金系统表',
            },
        ),
        migrations.CreateModel(
            name='BonusUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('安全测评', '安全测评'), ('等保测评', '等保测评')], max_length=30, verbose_name='系统性质')),
                ('unit', models.CharField(max_length=100, verbose_name='单位名称')),
                ('bonus', models.CharField(max_length=255, verbose_name='税前奖金')),
                ('pm', models.CharField(choices=[('1', '李海燕'), ('2', '段圣雄'), ('3', '朱贇'), ('4', '苏钰淇'), ('5', '银鹰'), ('6', '张鑫'), ('7', '金俊'), ('8', '颜星晨'), ('9', '王栋'), ('10', '杨华'), ('11', '侍国亮'), ('12', '张保稳'), ('13', '张全海'), ('14', '陈秀真'), ('15', '周志洪'), ('16', '夏正敏'), ('17', '沈瑜')], max_length=30, verbose_name='项目经理')),
                ('sale', models.CharField(choices=[('1', '李海燕'), ('2', '段圣雄'), ('3', '朱贇'), ('4', '苏钰淇'), ('5', '银鹰'), ('6', '张鑫'), ('7', '金俊'), ('8', '颜星晨'), ('9', '王栋'), ('10', '杨华'), ('11', '侍国亮'), ('12', '张保稳'), ('13', '张全海'), ('14', '陈秀真'), ('15', '周志洪'), ('16', '夏正敏'), ('17', '沈瑜')], max_length=30, verbose_name='商务')),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='contract_pdf', verbose_name='合同文件')),
                ('remarks', models.CharField(max_length=255, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '奖金单位表',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseUpload', models.FileField(blank=True, null=True, upload_to='caseUpload', verbose_name='上传方案')),
                ('caseDown', models.FileField(blank=True, null=True, upload_to='caseDown', verbose_name='下载方案')),
            ],
        ),
        migrations.CreateModel(
            name='CUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='联系人名字')),
                ('email', models.EmailField(max_length=100, verbose_name='邮箱')),
                ('post', models.CharField(max_length=30, verbose_name='岗位')),
                ('phone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('telephone', models.CharField(max_length=11, verbose_name='手机')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '客户方联系人信息',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=30, verbose_name='单位名称')),
                ('company_profile', models.TextField(max_length=300, verbose_name='单位简介')),
                ('address', models.CharField(max_length=255, verbose_name='单位地址')),
                ('nature', models.CharField(choices=[('1', '党政机关'), ('2', '国家重要行业、重要领域或重要企事业单位'), ('3', '一般企事业单位'), ('4', '其他类型')], max_length=30, verbose_name='单位性质')),
                ('code', models.CharField(max_length=30, verbose_name='邮编')),
                ('department', models.CharField(max_length=30, verbose_name='部门')),
                ('superdepar', models.CharField(max_length=30, verbose_name='上级主管部门')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='单位与添加人员关联表')),
            ],
            options={
                'verbose_name_plural': '客户单位信息表',
            },
        ),
        migrations.CreateModel(
            name='Djcp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(verbose_name='备注')),
                ('cuserInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcp.CUserInfo', verbose_name='联系人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcp.Customer', verbose_name='单位')),
            ],
        ),
        migrations.CreateModel(
            name='GmanagerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmanager', models.CharField(max_length=30, verbose_name='负责人名字')),
                ('gphone', models.CharField(max_length=11, verbose_name='负责人办公电话')),
                ('gtelephone', models.CharField(max_length=11, verbose_name='负责人手机')),
                ('gpost', models.CharField(max_length=30, verbose_name='负责人岗位')),
                ('gemail', models.EmailField(max_length=100, verbose_name='负责人邮箱')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('gnameinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcp.Customer', verbose_name='单位负责人和单位关联表')),
            ],
            options={
                'verbose_name_plural': '客户方负责人信息',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zc_excel', models.FileField(blank=True, null=True, upload_to='infocheck', verbose_name='资产表excel')),
                ('tpt', models.FileField(blank=True, null=True, upload_to='tpt', verbose_name='拓扑图')),
                ('tpt_desc', models.TextField(verbose_name='拓扑图描述')),
                ('downloadinfo', models.FileField(blank=True, null=True, upload_to='downloadinfo', verbose_name='下载信调表')),
                ('djcp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcp.Djcp', verbose_name='项目')),
            ],
        ),
        migrations.CreateModel(
            name='ProDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply', models.CharField(max_length=32, verbose_name='测评申请书')),
                ('accept', models.CharField(max_length=32, verbose_name='文档接受清单')),
                ('formalization', models.CharField(max_length=32, verbose_name='形式化审查意见')),
                ('contract', models.CharField(max_length=32, verbose_name='测评服务合同')),
                ('secret', models.CharField(max_length=32, verbose_name='保密协议')),
                ('authorization', models.CharField(max_length=32, verbose_name='授权委托书')),
                ('task', models.CharField(max_length=32, verbose_name='项目任务书')),
                ('question', models.CharField(max_length=32, verbose_name='基本信息调查表')),
                ('scheme', models.CharField(max_length=32, verbose_name='方案编制')),
                ('schemereview', models.CharField(max_length=32, verbose_name='方案评审')),
                ('firstmeeting', models.CharField(max_length=32, verbose_name='首次会议')),
                ('onsiteevalaation', models.CharField(max_length=32, verbose_name='现场测评授权书')),
                ('record', models.CharField(max_length=32, verbose_name='安全等级测评记录表 ')),
                ('test', models.CharField(max_length=32, verbose_name='检验监督记录')),
                ('lasttmeeting', models.CharField(max_length=32, verbose_name='末次会议')),
                ('reporter_date', models.CharField(max_length=32, verbose_name='测评报告')),
                ('reporterview', models.CharField(max_length=32, verbose_name='测评报告评审')),
                ('acceptreporter', models.CharField(max_length=32, verbose_name='测评报告接收单')),
                ('agreen', models.CharField(max_length=32, verbose_name='客户满意度问卷调查')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcp.Customer', verbose_name='时间和客户单位关系表')),
            ],
            options={
                'verbose_name_plural': '项目时间表',
            },
        ),
        migrations.CreateModel(
            name='ProInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=30, verbose_name='项目名称')),
                ('agentname', models.CharField(blank=True, max_length=30, null=True, verbose_name='中间商单位名称')),
                ('sys_name', models.CharField(max_length=30, verbose_name='系统名称')),
                ('level', models.CharField(choices=[('1', 'S2A2G2'), ('2', 'S2A1G2'), ('3', 'S1A2G2'), ('4', 'S3A3G3'), ('5', 'S3A2G3'), ('6', 'S2A3G3')], max_length=20, verbose_name='系统级别')),
                ('sys_service', models.CharField(choices=[('1', '业务专网'), ('2', '互联网'), ('3', '其他')], max_length=30, verbose_name='系统服务性质')),
                ('sys_obj', models.CharField(choices=[('1', '单位内部人员'), ('2', '社会公众人员'), ('3', '二者均包括'), ('4', '其他')], max_length=20, verbose_name='系统服务对象')),
                ('pro_num', models.CharField(blank=True, max_length=30, null=True, verbose_name='项目编号')),
                ('Record_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='备案编号')),
                ('pm', models.CharField(max_length=100, verbose_name='项目经理')),
                ('supervisor', models.CharField(max_length=100, verbose_name='监督人')),
                ('reporter_pro', models.CharField(max_length=100, verbose_name='汇报人')),
                ('supervisored', models.CharField(max_length=100, verbose_name='被监督人')),
                ('desc', models.CharField(max_length=255, verbose_name='业务描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('proinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcp.Customer', verbose_name='项目和客户单位管理表')),
            ],
            options={
                'verbose_name_plural': '项目信息表',
            },
        ),
        migrations.AddField(
            model_name='djcp',
            name='gmanagerInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcp.GmanagerInfo', verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='djcp',
            name='proInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcp.ProInfo', verbose_name='系统'),
        ),
        migrations.AddField(
            model_name='djcp',
            name='prodate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcp.ProDate', verbose_name='测评服务合同'),
        ),
        migrations.AddField(
            model_name='cuserinfo',
            name='nameinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcp.Customer', verbose_name='单位联系人和单位关联表'),
        ),
        migrations.AddField(
            model_name='case',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcp.Djcp', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='bonusunit',
            name='bonus_pro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djcp.ProInfo', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='bonusunit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='bonussystem',
            name='bonusunit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcp.BonusUnit', verbose_name='奖金单位表'),
        ),
    ]
